// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: crib/creditfacility/v1/credit_facility.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "crib.creditfacility.v1";

export enum PaymentStatus {
  PAYMENT_STATUS_UNSPECIFIED = 0,
  ON_TIME = 1,
  LATE = 2,
  MISSED = 3,
  UNRECOGNIZED = -1,
}

export function paymentStatusFromJSON(object: any): PaymentStatus {
  switch (object) {
    case 0:
    case "PAYMENT_STATUS_UNSPECIFIED":
      return PaymentStatus.PAYMENT_STATUS_UNSPECIFIED;
    case 1:
    case "ON_TIME":
      return PaymentStatus.ON_TIME;
    case 2:
    case "LATE":
      return PaymentStatus.LATE;
    case 3:
    case "MISSED":
      return PaymentStatus.MISSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentStatus.UNRECOGNIZED;
  }
}

export function paymentStatusToJSON(object: PaymentStatus): string {
  switch (object) {
    case PaymentStatus.PAYMENT_STATUS_UNSPECIFIED:
      return "PAYMENT_STATUS_UNSPECIFIED";
    case PaymentStatus.ON_TIME:
      return "ON_TIME";
    case PaymentStatus.LATE:
      return "LATE";
    case PaymentStatus.MISSED:
      return "MISSED";
    case PaymentStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** CreditFacility defines the CreditFacility message. */
export interface CreditFacility {
  facilityId: string;
  cribUsernic: string;
  licenseNumber: string;
  institution: string;
  facilityType: string;
  loanAmount: number;
  outstandingBalance: number;
  status: string;
  openedDate: string;
  closedDate: string;
  paymentHistory: PaymentRecord[];
  creator: string;
}

export interface PaymentRecord {
  paymentId: string;
  date: string;
  amount: number;
  status: PaymentStatus;
}

function createBaseCreditFacility(): CreditFacility {
  return {
    facilityId: "",
    cribUsernic: "",
    licenseNumber: "",
    institution: "",
    facilityType: "",
    loanAmount: 0,
    outstandingBalance: 0,
    status: "",
    openedDate: "",
    closedDate: "",
    paymentHistory: [],
    creator: "",
  };
}

export const CreditFacility: MessageFns<CreditFacility> = {
  encode(message: CreditFacility, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.facilityId !== "") {
      writer.uint32(10).string(message.facilityId);
    }
    if (message.cribUsernic !== "") {
      writer.uint32(18).string(message.cribUsernic);
    }
    if (message.licenseNumber !== "") {
      writer.uint32(26).string(message.licenseNumber);
    }
    if (message.institution !== "") {
      writer.uint32(34).string(message.institution);
    }
    if (message.facilityType !== "") {
      writer.uint32(42).string(message.facilityType);
    }
    if (message.loanAmount !== 0) {
      writer.uint32(48).uint64(message.loanAmount);
    }
    if (message.outstandingBalance !== 0) {
      writer.uint32(56).uint64(message.outstandingBalance);
    }
    if (message.status !== "") {
      writer.uint32(66).string(message.status);
    }
    if (message.openedDate !== "") {
      writer.uint32(74).string(message.openedDate);
    }
    if (message.closedDate !== "") {
      writer.uint32(82).string(message.closedDate);
    }
    for (const v of message.paymentHistory) {
      PaymentRecord.encode(v!, writer.uint32(90).fork()).join();
    }
    if (message.creator !== "") {
      writer.uint32(98).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreditFacility {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreditFacility();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.facilityId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cribUsernic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.licenseNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.institution = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.facilityType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.loanAmount = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.outstandingBalance = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.openedDate = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.closedDate = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.paymentHistory.push(PaymentRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreditFacility {
    return {
      facilityId: isSet(object.facilityId) ? globalThis.String(object.facilityId) : "",
      cribUsernic: isSet(object.cribUsernic) ? globalThis.String(object.cribUsernic) : "",
      licenseNumber: isSet(object.licenseNumber) ? globalThis.String(object.licenseNumber) : "",
      institution: isSet(object.institution) ? globalThis.String(object.institution) : "",
      facilityType: isSet(object.facilityType) ? globalThis.String(object.facilityType) : "",
      loanAmount: isSet(object.loanAmount) ? globalThis.Number(object.loanAmount) : 0,
      outstandingBalance: isSet(object.outstandingBalance) ? globalThis.Number(object.outstandingBalance) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      openedDate: isSet(object.openedDate) ? globalThis.String(object.openedDate) : "",
      closedDate: isSet(object.closedDate) ? globalThis.String(object.closedDate) : "",
      paymentHistory: globalThis.Array.isArray(object?.paymentHistory)
        ? object.paymentHistory.map((e: any) => PaymentRecord.fromJSON(e))
        : [],
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: CreditFacility): unknown {
    const obj: any = {};
    if (message.facilityId !== "") {
      obj.facilityId = message.facilityId;
    }
    if (message.cribUsernic !== "") {
      obj.cribUsernic = message.cribUsernic;
    }
    if (message.licenseNumber !== "") {
      obj.licenseNumber = message.licenseNumber;
    }
    if (message.institution !== "") {
      obj.institution = message.institution;
    }
    if (message.facilityType !== "") {
      obj.facilityType = message.facilityType;
    }
    if (message.loanAmount !== 0) {
      obj.loanAmount = Math.round(message.loanAmount);
    }
    if (message.outstandingBalance !== 0) {
      obj.outstandingBalance = Math.round(message.outstandingBalance);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.openedDate !== "") {
      obj.openedDate = message.openedDate;
    }
    if (message.closedDate !== "") {
      obj.closedDate = message.closedDate;
    }
    if (message.paymentHistory?.length) {
      obj.paymentHistory = message.paymentHistory.map((e) => PaymentRecord.toJSON(e));
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreditFacility>, I>>(base?: I): CreditFacility {
    return CreditFacility.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreditFacility>, I>>(object: I): CreditFacility {
    const message = createBaseCreditFacility();
    message.facilityId = object.facilityId ?? "";
    message.cribUsernic = object.cribUsernic ?? "";
    message.licenseNumber = object.licenseNumber ?? "";
    message.institution = object.institution ?? "";
    message.facilityType = object.facilityType ?? "";
    message.loanAmount = object.loanAmount ?? 0;
    message.outstandingBalance = object.outstandingBalance ?? 0;
    message.status = object.status ?? "";
    message.openedDate = object.openedDate ?? "";
    message.closedDate = object.closedDate ?? "";
    message.paymentHistory = object.paymentHistory?.map((e) => PaymentRecord.fromPartial(e)) || [];
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBasePaymentRecord(): PaymentRecord {
  return { paymentId: "", date: "", amount: 0, status: 0 };
}

export const PaymentRecord: MessageFns<PaymentRecord> = {
  encode(message: PaymentRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.paymentId !== "") {
      writer.uint32(10).string(message.paymentId);
    }
    if (message.date !== "") {
      writer.uint32(18).string(message.date);
    }
    if (message.amount !== 0) {
      writer.uint32(24).uint64(message.amount);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaymentRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaymentRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.paymentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.amount = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaymentRecord {
    return {
      paymentId: isSet(object.paymentId) ? globalThis.String(object.paymentId) : "",
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      status: isSet(object.status) ? paymentStatusFromJSON(object.status) : 0,
    };
  },

  toJSON(message: PaymentRecord): unknown {
    const obj: any = {};
    if (message.paymentId !== "") {
      obj.paymentId = message.paymentId;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.status !== 0) {
      obj.status = paymentStatusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaymentRecord>, I>>(base?: I): PaymentRecord {
    return PaymentRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaymentRecord>, I>>(object: I): PaymentRecord {
    const message = createBasePaymentRecord();
    message.paymentId = object.paymentId ?? "";
    message.date = object.date ?? "";
    message.amount = object.amount ?? 0;
    message.status = object.status ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
