// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: crib/creditfacility/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { CreditFacility } from "./credit_facility";
import { Params } from "./params";

export const protobufPackage = "crib.creditfacility.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryGetCreditFacilityRequest defines the QueryGetCreditFacilityRequest message. */
export interface QueryGetCreditFacilityRequest {
  facilityId: string;
}

/** QueryGetCreditFacilityResponse defines the QueryGetCreditFacilityResponse message. */
export interface QueryGetCreditFacilityResponse {
  status: string;
  code: number;
  message: string;
  creditFacility: CreditFacility | undefined;
  requestId: string;
  timestamp: string;
}

/** QueryAllCreditFacilityRequest defines the QueryAllCreditFacilityRequest message. */
export interface QueryAllCreditFacilityRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllCreditFacilityResponse defines the QueryAllCreditFacilityResponse message. */
export interface QueryAllCreditFacilityResponse {
  creditFacility: CreditFacility[];
  pagination: PageResponse | undefined;
}

/** QueryListCreditFacilityByNicRequest defines the QueryListCreditFacilityByNicRequest message. */
export interface QueryListCreditFacilityByNicRequest {
  nic: string;
}

/** QueryListCreditFacilityByNicResponse defines the QueryListCreditFacilityByNicResponse message. */
export interface QueryListCreditFacilityByNicResponse {
  status: string;
  code: number;
  message: string;
  creditFacility: CreditFacility[];
  requestId: string;
  timestamp: string;
}

/** QueryCribReportRequest defines the QueryCribReportRequest message. */
export interface QueryCribReportRequest {
  nic: string;
}

export interface CribAccount {
  nic: string;
  cribId: string;
  fullName: string;
  dateOfBirth: string;
  isActive: boolean;
  phoneNumber: string;
  email: string;
  nicFrontCid: string;
  nicBackCid: string;
  createdBy: string;
  createdAt: string;
  creator: string;
}

/** QueryCribReportResponse defines the QueryCribReportResponse message. */
export interface CribReport {
  cribAccountDetails: CribAccount | undefined;
  creditFacilities: CreditFacility[];
  totalFacilities: number;
  activeFacilities: number;
  closedFacilities: number;
  totalLoanAmount: number;
  totalOutstanding: number;
  onTimePayments: number;
  latePayments: number;
  missedPayments: number;
  onTimePaymentRatio: number;
  creditScore: number;
}

export interface QueryCribReportResponse {
  status: string;
  code: number;
  message: string;
  cribReport: CribReport | undefined;
  requestId: string;
  timestamp: string;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetCreditFacilityRequest(): QueryGetCreditFacilityRequest {
  return { facilityId: "" };
}

export const QueryGetCreditFacilityRequest: MessageFns<QueryGetCreditFacilityRequest> = {
  encode(message: QueryGetCreditFacilityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.facilityId !== "") {
      writer.uint32(10).string(message.facilityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetCreditFacilityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetCreditFacilityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.facilityId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetCreditFacilityRequest {
    return { facilityId: isSet(object.facilityId) ? globalThis.String(object.facilityId) : "" };
  },

  toJSON(message: QueryGetCreditFacilityRequest): unknown {
    const obj: any = {};
    if (message.facilityId !== "") {
      obj.facilityId = message.facilityId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetCreditFacilityRequest>, I>>(base?: I): QueryGetCreditFacilityRequest {
    return QueryGetCreditFacilityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetCreditFacilityRequest>, I>>(
    object: I,
  ): QueryGetCreditFacilityRequest {
    const message = createBaseQueryGetCreditFacilityRequest();
    message.facilityId = object.facilityId ?? "";
    return message;
  },
};

function createBaseQueryGetCreditFacilityResponse(): QueryGetCreditFacilityResponse {
  return { status: "", code: 0, message: "", creditFacility: undefined, requestId: "", timestamp: "" };
}

export const QueryGetCreditFacilityResponse: MessageFns<QueryGetCreditFacilityResponse> = {
  encode(message: QueryGetCreditFacilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.creditFacility !== undefined) {
      CreditFacility.encode(message.creditFacility, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetCreditFacilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetCreditFacilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.creditFacility = CreditFacility.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetCreditFacilityResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      creditFacility: isSet(object.creditFacility) ? CreditFacility.fromJSON(object.creditFacility) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryGetCreditFacilityResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.creditFacility !== undefined) {
      obj.creditFacility = CreditFacility.toJSON(message.creditFacility);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetCreditFacilityResponse>, I>>(base?: I): QueryGetCreditFacilityResponse {
    return QueryGetCreditFacilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetCreditFacilityResponse>, I>>(
    object: I,
  ): QueryGetCreditFacilityResponse {
    const message = createBaseQueryGetCreditFacilityResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.creditFacility = (object.creditFacility !== undefined && object.creditFacility !== null)
      ? CreditFacility.fromPartial(object.creditFacility)
      : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryAllCreditFacilityRequest(): QueryAllCreditFacilityRequest {
  return { pagination: undefined };
}

export const QueryAllCreditFacilityRequest: MessageFns<QueryAllCreditFacilityRequest> = {
  encode(message: QueryAllCreditFacilityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllCreditFacilityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllCreditFacilityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllCreditFacilityRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllCreditFacilityRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllCreditFacilityRequest>, I>>(base?: I): QueryAllCreditFacilityRequest {
    return QueryAllCreditFacilityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllCreditFacilityRequest>, I>>(
    object: I,
  ): QueryAllCreditFacilityRequest {
    const message = createBaseQueryAllCreditFacilityRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllCreditFacilityResponse(): QueryAllCreditFacilityResponse {
  return { creditFacility: [], pagination: undefined };
}

export const QueryAllCreditFacilityResponse: MessageFns<QueryAllCreditFacilityResponse> = {
  encode(message: QueryAllCreditFacilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.creditFacility) {
      CreditFacility.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllCreditFacilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllCreditFacilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creditFacility.push(CreditFacility.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllCreditFacilityResponse {
    return {
      creditFacility: globalThis.Array.isArray(object?.creditFacility)
        ? object.creditFacility.map((e: any) => CreditFacility.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllCreditFacilityResponse): unknown {
    const obj: any = {};
    if (message.creditFacility?.length) {
      obj.creditFacility = message.creditFacility.map((e) => CreditFacility.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllCreditFacilityResponse>, I>>(base?: I): QueryAllCreditFacilityResponse {
    return QueryAllCreditFacilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllCreditFacilityResponse>, I>>(
    object: I,
  ): QueryAllCreditFacilityResponse {
    const message = createBaseQueryAllCreditFacilityResponse();
    message.creditFacility = object.creditFacility?.map((e) => CreditFacility.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryListCreditFacilityByNicRequest(): QueryListCreditFacilityByNicRequest {
  return { nic: "" };
}

export const QueryListCreditFacilityByNicRequest: MessageFns<QueryListCreditFacilityByNicRequest> = {
  encode(message: QueryListCreditFacilityByNicRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nic !== "") {
      writer.uint32(10).string(message.nic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListCreditFacilityByNicRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListCreditFacilityByNicRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListCreditFacilityByNicRequest {
    return { nic: isSet(object.nic) ? globalThis.String(object.nic) : "" };
  },

  toJSON(message: QueryListCreditFacilityByNicRequest): unknown {
    const obj: any = {};
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListCreditFacilityByNicRequest>, I>>(
    base?: I,
  ): QueryListCreditFacilityByNicRequest {
    return QueryListCreditFacilityByNicRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListCreditFacilityByNicRequest>, I>>(
    object: I,
  ): QueryListCreditFacilityByNicRequest {
    const message = createBaseQueryListCreditFacilityByNicRequest();
    message.nic = object.nic ?? "";
    return message;
  },
};

function createBaseQueryListCreditFacilityByNicResponse(): QueryListCreditFacilityByNicResponse {
  return { status: "", code: 0, message: "", creditFacility: [], requestId: "", timestamp: "" };
}

export const QueryListCreditFacilityByNicResponse: MessageFns<QueryListCreditFacilityByNicResponse> = {
  encode(message: QueryListCreditFacilityByNicResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    for (const v of message.creditFacility) {
      CreditFacility.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListCreditFacilityByNicResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListCreditFacilityByNicResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.creditFacility.push(CreditFacility.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListCreditFacilityByNicResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      creditFacility: globalThis.Array.isArray(object?.creditFacility)
        ? object.creditFacility.map((e: any) => CreditFacility.fromJSON(e))
        : [],
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryListCreditFacilityByNicResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.creditFacility?.length) {
      obj.creditFacility = message.creditFacility.map((e) => CreditFacility.toJSON(e));
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListCreditFacilityByNicResponse>, I>>(
    base?: I,
  ): QueryListCreditFacilityByNicResponse {
    return QueryListCreditFacilityByNicResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListCreditFacilityByNicResponse>, I>>(
    object: I,
  ): QueryListCreditFacilityByNicResponse {
    const message = createBaseQueryListCreditFacilityByNicResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.creditFacility = object.creditFacility?.map((e) => CreditFacility.fromPartial(e)) || [];
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryCribReportRequest(): QueryCribReportRequest {
  return { nic: "" };
}

export const QueryCribReportRequest: MessageFns<QueryCribReportRequest> = {
  encode(message: QueryCribReportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nic !== "") {
      writer.uint32(10).string(message.nic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCribReportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCribReportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCribReportRequest {
    return { nic: isSet(object.nic) ? globalThis.String(object.nic) : "" };
  },

  toJSON(message: QueryCribReportRequest): unknown {
    const obj: any = {};
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCribReportRequest>, I>>(base?: I): QueryCribReportRequest {
    return QueryCribReportRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCribReportRequest>, I>>(object: I): QueryCribReportRequest {
    const message = createBaseQueryCribReportRequest();
    message.nic = object.nic ?? "";
    return message;
  },
};

function createBaseCribAccount(): CribAccount {
  return {
    nic: "",
    cribId: "",
    fullName: "",
    dateOfBirth: "",
    isActive: false,
    phoneNumber: "",
    email: "",
    nicFrontCid: "",
    nicBackCid: "",
    createdBy: "",
    createdAt: "",
    creator: "",
  };
}

export const CribAccount: MessageFns<CribAccount> = {
  encode(message: CribAccount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nic !== "") {
      writer.uint32(10).string(message.nic);
    }
    if (message.cribId !== "") {
      writer.uint32(18).string(message.cribId);
    }
    if (message.fullName !== "") {
      writer.uint32(26).string(message.fullName);
    }
    if (message.dateOfBirth !== "") {
      writer.uint32(34).string(message.dateOfBirth);
    }
    if (message.isActive !== false) {
      writer.uint32(40).bool(message.isActive);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(50).string(message.phoneNumber);
    }
    if (message.email !== "") {
      writer.uint32(58).string(message.email);
    }
    if (message.nicFrontCid !== "") {
      writer.uint32(66).string(message.nicFrontCid);
    }
    if (message.nicBackCid !== "") {
      writer.uint32(74).string(message.nicBackCid);
    }
    if (message.createdBy !== "") {
      writer.uint32(82).string(message.createdBy);
    }
    if (message.createdAt !== "") {
      writer.uint32(90).string(message.createdAt);
    }
    if (message.creator !== "") {
      writer.uint32(98).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CribAccount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCribAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cribId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fullName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dateOfBirth = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nicFrontCid = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.nicBackCid = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.createdBy = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CribAccount {
    return {
      nic: isSet(object.nic) ? globalThis.String(object.nic) : "",
      cribId: isSet(object.cribId) ? globalThis.String(object.cribId) : "",
      fullName: isSet(object.fullName) ? globalThis.String(object.fullName) : "",
      dateOfBirth: isSet(object.dateOfBirth) ? globalThis.String(object.dateOfBirth) : "",
      isActive: isSet(object.isActive) ? globalThis.Boolean(object.isActive) : false,
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      nicFrontCid: isSet(object.nicFrontCid) ? globalThis.String(object.nicFrontCid) : "",
      nicBackCid: isSet(object.nicBackCid) ? globalThis.String(object.nicBackCid) : "",
      createdBy: isSet(object.createdBy) ? globalThis.String(object.createdBy) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: CribAccount): unknown {
    const obj: any = {};
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    if (message.cribId !== "") {
      obj.cribId = message.cribId;
    }
    if (message.fullName !== "") {
      obj.fullName = message.fullName;
    }
    if (message.dateOfBirth !== "") {
      obj.dateOfBirth = message.dateOfBirth;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.nicFrontCid !== "") {
      obj.nicFrontCid = message.nicFrontCid;
    }
    if (message.nicBackCid !== "") {
      obj.nicBackCid = message.nicBackCid;
    }
    if (message.createdBy !== "") {
      obj.createdBy = message.createdBy;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CribAccount>, I>>(base?: I): CribAccount {
    return CribAccount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CribAccount>, I>>(object: I): CribAccount {
    const message = createBaseCribAccount();
    message.nic = object.nic ?? "";
    message.cribId = object.cribId ?? "";
    message.fullName = object.fullName ?? "";
    message.dateOfBirth = object.dateOfBirth ?? "";
    message.isActive = object.isActive ?? false;
    message.phoneNumber = object.phoneNumber ?? "";
    message.email = object.email ?? "";
    message.nicFrontCid = object.nicFrontCid ?? "";
    message.nicBackCid = object.nicBackCid ?? "";
    message.createdBy = object.createdBy ?? "";
    message.createdAt = object.createdAt ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseCribReport(): CribReport {
  return {
    cribAccountDetails: undefined,
    creditFacilities: [],
    totalFacilities: 0,
    activeFacilities: 0,
    closedFacilities: 0,
    totalLoanAmount: 0,
    totalOutstanding: 0,
    onTimePayments: 0,
    latePayments: 0,
    missedPayments: 0,
    onTimePaymentRatio: 0,
    creditScore: 0,
  };
}

export const CribReport: MessageFns<CribReport> = {
  encode(message: CribReport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cribAccountDetails !== undefined) {
      CribAccount.encode(message.cribAccountDetails, writer.uint32(10).fork()).join();
    }
    for (const v of message.creditFacilities) {
      CreditFacility.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.totalFacilities !== 0) {
      writer.uint32(24).uint32(message.totalFacilities);
    }
    if (message.activeFacilities !== 0) {
      writer.uint32(32).uint32(message.activeFacilities);
    }
    if (message.closedFacilities !== 0) {
      writer.uint32(40).uint32(message.closedFacilities);
    }
    if (message.totalLoanAmount !== 0) {
      writer.uint32(48).uint64(message.totalLoanAmount);
    }
    if (message.totalOutstanding !== 0) {
      writer.uint32(56).uint64(message.totalOutstanding);
    }
    if (message.onTimePayments !== 0) {
      writer.uint32(64).uint32(message.onTimePayments);
    }
    if (message.latePayments !== 0) {
      writer.uint32(72).uint32(message.latePayments);
    }
    if (message.missedPayments !== 0) {
      writer.uint32(80).uint32(message.missedPayments);
    }
    if (message.onTimePaymentRatio !== 0) {
      writer.uint32(93).float(message.onTimePaymentRatio);
    }
    if (message.creditScore !== 0) {
      writer.uint32(96).uint32(message.creditScore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CribReport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCribReport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cribAccountDetails = CribAccount.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.creditFacilities.push(CreditFacility.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalFacilities = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.activeFacilities = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.closedFacilities = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalLoanAmount = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalOutstanding = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.onTimePayments = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.latePayments = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.missedPayments = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 93) {
            break;
          }

          message.onTimePaymentRatio = reader.float();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.creditScore = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CribReport {
    return {
      cribAccountDetails: isSet(object.cribAccountDetails)
        ? CribAccount.fromJSON(object.cribAccountDetails)
        : undefined,
      creditFacilities: globalThis.Array.isArray(object?.creditFacilities)
        ? object.creditFacilities.map((e: any) => CreditFacility.fromJSON(e))
        : [],
      totalFacilities: isSet(object.totalFacilities) ? globalThis.Number(object.totalFacilities) : 0,
      activeFacilities: isSet(object.activeFacilities) ? globalThis.Number(object.activeFacilities) : 0,
      closedFacilities: isSet(object.closedFacilities) ? globalThis.Number(object.closedFacilities) : 0,
      totalLoanAmount: isSet(object.totalLoanAmount) ? globalThis.Number(object.totalLoanAmount) : 0,
      totalOutstanding: isSet(object.totalOutstanding) ? globalThis.Number(object.totalOutstanding) : 0,
      onTimePayments: isSet(object.onTimePayments) ? globalThis.Number(object.onTimePayments) : 0,
      latePayments: isSet(object.latePayments) ? globalThis.Number(object.latePayments) : 0,
      missedPayments: isSet(object.missedPayments) ? globalThis.Number(object.missedPayments) : 0,
      onTimePaymentRatio: isSet(object.onTimePaymentRatio) ? globalThis.Number(object.onTimePaymentRatio) : 0,
      creditScore: isSet(object.creditScore) ? globalThis.Number(object.creditScore) : 0,
    };
  },

  toJSON(message: CribReport): unknown {
    const obj: any = {};
    if (message.cribAccountDetails !== undefined) {
      obj.cribAccountDetails = CribAccount.toJSON(message.cribAccountDetails);
    }
    if (message.creditFacilities?.length) {
      obj.creditFacilities = message.creditFacilities.map((e) => CreditFacility.toJSON(e));
    }
    if (message.totalFacilities !== 0) {
      obj.totalFacilities = Math.round(message.totalFacilities);
    }
    if (message.activeFacilities !== 0) {
      obj.activeFacilities = Math.round(message.activeFacilities);
    }
    if (message.closedFacilities !== 0) {
      obj.closedFacilities = Math.round(message.closedFacilities);
    }
    if (message.totalLoanAmount !== 0) {
      obj.totalLoanAmount = Math.round(message.totalLoanAmount);
    }
    if (message.totalOutstanding !== 0) {
      obj.totalOutstanding = Math.round(message.totalOutstanding);
    }
    if (message.onTimePayments !== 0) {
      obj.onTimePayments = Math.round(message.onTimePayments);
    }
    if (message.latePayments !== 0) {
      obj.latePayments = Math.round(message.latePayments);
    }
    if (message.missedPayments !== 0) {
      obj.missedPayments = Math.round(message.missedPayments);
    }
    if (message.onTimePaymentRatio !== 0) {
      obj.onTimePaymentRatio = message.onTimePaymentRatio;
    }
    if (message.creditScore !== 0) {
      obj.creditScore = Math.round(message.creditScore);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CribReport>, I>>(base?: I): CribReport {
    return CribReport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CribReport>, I>>(object: I): CribReport {
    const message = createBaseCribReport();
    message.cribAccountDetails = (object.cribAccountDetails !== undefined && object.cribAccountDetails !== null)
      ? CribAccount.fromPartial(object.cribAccountDetails)
      : undefined;
    message.creditFacilities = object.creditFacilities?.map((e) => CreditFacility.fromPartial(e)) || [];
    message.totalFacilities = object.totalFacilities ?? 0;
    message.activeFacilities = object.activeFacilities ?? 0;
    message.closedFacilities = object.closedFacilities ?? 0;
    message.totalLoanAmount = object.totalLoanAmount ?? 0;
    message.totalOutstanding = object.totalOutstanding ?? 0;
    message.onTimePayments = object.onTimePayments ?? 0;
    message.latePayments = object.latePayments ?? 0;
    message.missedPayments = object.missedPayments ?? 0;
    message.onTimePaymentRatio = object.onTimePaymentRatio ?? 0;
    message.creditScore = object.creditScore ?? 0;
    return message;
  },
};

function createBaseQueryCribReportResponse(): QueryCribReportResponse {
  return { status: "", code: 0, message: "", cribReport: undefined, requestId: "", timestamp: "" };
}

export const QueryCribReportResponse: MessageFns<QueryCribReportResponse> = {
  encode(message: QueryCribReportResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.cribReport !== undefined) {
      CribReport.encode(message.cribReport, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCribReportResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCribReportResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cribReport = CribReport.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCribReportResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      cribReport: isSet(object.cribReport) ? CribReport.fromJSON(object.cribReport) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryCribReportResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.cribReport !== undefined) {
      obj.cribReport = CribReport.toJSON(message.cribReport);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCribReportResponse>, I>>(base?: I): QueryCribReportResponse {
    return QueryCribReportResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCribReportResponse>, I>>(object: I): QueryCribReportResponse {
    const message = createBaseQueryCribReportResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.cribReport = (object.cribReport !== undefined && object.cribReport !== null)
      ? CribReport.fromPartial(object.cribReport)
      : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** ListCreditFacility Queries a list of CreditFacility items. */
  GetCreditFacility(request: QueryGetCreditFacilityRequest): Promise<QueryGetCreditFacilityResponse>;
  /** ListCreditFacility defines the ListCreditFacility RPC. */
  ListCreditFacility(request: QueryAllCreditFacilityRequest): Promise<QueryAllCreditFacilityResponse>;
  /** ListCreditFacilityByNic Queries a list of ListCreditFacilityByNic items. */
  ListCreditFacilityByNic(request: QueryListCreditFacilityByNicRequest): Promise<QueryListCreditFacilityByNicResponse>;
  /** CribReport Queries a list of CribReport items. */
  CribReport(request: QueryCribReportRequest): Promise<QueryCribReportResponse>;
}

export const QueryServiceName = "crib.creditfacility.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.GetCreditFacility = this.GetCreditFacility.bind(this);
    this.ListCreditFacility = this.ListCreditFacility.bind(this);
    this.ListCreditFacilityByNic = this.ListCreditFacilityByNic.bind(this);
    this.CribReport = this.CribReport.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  GetCreditFacility(request: QueryGetCreditFacilityRequest): Promise<QueryGetCreditFacilityResponse> {
    const data = QueryGetCreditFacilityRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetCreditFacility", data);
    return promise.then((data) => QueryGetCreditFacilityResponse.decode(new BinaryReader(data)));
  }

  ListCreditFacility(request: QueryAllCreditFacilityRequest): Promise<QueryAllCreditFacilityResponse> {
    const data = QueryAllCreditFacilityRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListCreditFacility", data);
    return promise.then((data) => QueryAllCreditFacilityResponse.decode(new BinaryReader(data)));
  }

  ListCreditFacilityByNic(request: QueryListCreditFacilityByNicRequest): Promise<QueryListCreditFacilityByNicResponse> {
    const data = QueryListCreditFacilityByNicRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListCreditFacilityByNic", data);
    return promise.then((data) => QueryListCreditFacilityByNicResponse.decode(new BinaryReader(data)));
  }

  CribReport(request: QueryCribReportRequest): Promise<QueryCribReportResponse> {
    const data = QueryCribReportRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CribReport", data);
    return promise.then((data) => QueryCribReportResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
