// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: crib/creditfacility/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FacilityStatus, facilityStatusFromJSON, facilityStatusToJSON, PaymentRecord } from "./credit_facility";
import { Params } from "./params";

export const protobufPackage = "crib.creditfacility.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgCreateCreditFacility defines the MsgCreateCreditFacility message. */
export interface MsgCreateCreditFacility {
  creator: string;
  cribUsernic: string;
  licenseNumber: string;
  institution: string;
  facilityType: string;
  loanAmount: number;
  status: FacilityStatus;
  openedDate: string;
  closedDate: string;
  paymentHistory: PaymentRecord[];
}

/** MsgCreateCreditFacilityResponse defines the MsgCreateCreditFacilityResponse message. */
export interface MsgCreateCreditFacilityResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

/** MsgUpdateCreditFacility defines the MsgUpdateCreditFacility message. */
export interface MsgUpdateCreditFacility {
  creator: string;
  facilityId: string;
  cribUserNic: string;
  status: FacilityStatus;
  paymentHistory: PaymentRecord[];
}

/** MsgUpdateCreditFacilityResponse defines the MsgUpdateCreditFacilityResponse message. */
export interface MsgUpdateCreditFacilityResponse {
  status: string;
  code: number;
  message: string;
  data: string;
  requestId: string;
  timestamp: string;
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreateCreditFacility(): MsgCreateCreditFacility {
  return {
    creator: "",
    cribUsernic: "",
    licenseNumber: "",
    institution: "",
    facilityType: "",
    loanAmount: 0,
    status: 0,
    openedDate: "",
    closedDate: "",
    paymentHistory: [],
  };
}

export const MsgCreateCreditFacility: MessageFns<MsgCreateCreditFacility> = {
  encode(message: MsgCreateCreditFacility, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.cribUsernic !== "") {
      writer.uint32(18).string(message.cribUsernic);
    }
    if (message.licenseNumber !== "") {
      writer.uint32(26).string(message.licenseNumber);
    }
    if (message.institution !== "") {
      writer.uint32(34).string(message.institution);
    }
    if (message.facilityType !== "") {
      writer.uint32(42).string(message.facilityType);
    }
    if (message.loanAmount !== 0) {
      writer.uint32(48).uint64(message.loanAmount);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.openedDate !== "") {
      writer.uint32(66).string(message.openedDate);
    }
    if (message.closedDate !== "") {
      writer.uint32(74).string(message.closedDate);
    }
    for (const v of message.paymentHistory) {
      PaymentRecord.encode(v!, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateCreditFacility {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateCreditFacility();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cribUsernic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.licenseNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.institution = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.facilityType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.loanAmount = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.openedDate = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.closedDate = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.paymentHistory.push(PaymentRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateCreditFacility {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      cribUsernic: isSet(object.cribUsernic) ? globalThis.String(object.cribUsernic) : "",
      licenseNumber: isSet(object.licenseNumber) ? globalThis.String(object.licenseNumber) : "",
      institution: isSet(object.institution) ? globalThis.String(object.institution) : "",
      facilityType: isSet(object.facilityType) ? globalThis.String(object.facilityType) : "",
      loanAmount: isSet(object.loanAmount) ? globalThis.Number(object.loanAmount) : 0,
      status: isSet(object.status) ? facilityStatusFromJSON(object.status) : 0,
      openedDate: isSet(object.openedDate) ? globalThis.String(object.openedDate) : "",
      closedDate: isSet(object.closedDate) ? globalThis.String(object.closedDate) : "",
      paymentHistory: globalThis.Array.isArray(object?.paymentHistory)
        ? object.paymentHistory.map((e: any) => PaymentRecord.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MsgCreateCreditFacility): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.cribUsernic !== "") {
      obj.cribUsernic = message.cribUsernic;
    }
    if (message.licenseNumber !== "") {
      obj.licenseNumber = message.licenseNumber;
    }
    if (message.institution !== "") {
      obj.institution = message.institution;
    }
    if (message.facilityType !== "") {
      obj.facilityType = message.facilityType;
    }
    if (message.loanAmount !== 0) {
      obj.loanAmount = Math.round(message.loanAmount);
    }
    if (message.status !== 0) {
      obj.status = facilityStatusToJSON(message.status);
    }
    if (message.openedDate !== "") {
      obj.openedDate = message.openedDate;
    }
    if (message.closedDate !== "") {
      obj.closedDate = message.closedDate;
    }
    if (message.paymentHistory?.length) {
      obj.paymentHistory = message.paymentHistory.map((e) => PaymentRecord.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateCreditFacility>, I>>(base?: I): MsgCreateCreditFacility {
    return MsgCreateCreditFacility.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateCreditFacility>, I>>(object: I): MsgCreateCreditFacility {
    const message = createBaseMsgCreateCreditFacility();
    message.creator = object.creator ?? "";
    message.cribUsernic = object.cribUsernic ?? "";
    message.licenseNumber = object.licenseNumber ?? "";
    message.institution = object.institution ?? "";
    message.facilityType = object.facilityType ?? "";
    message.loanAmount = object.loanAmount ?? 0;
    message.status = object.status ?? 0;
    message.openedDate = object.openedDate ?? "";
    message.closedDate = object.closedDate ?? "";
    message.paymentHistory = object.paymentHistory?.map((e) => PaymentRecord.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMsgCreateCreditFacilityResponse(): MsgCreateCreditFacilityResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgCreateCreditFacilityResponse: MessageFns<MsgCreateCreditFacilityResponse> = {
  encode(message: MsgCreateCreditFacilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateCreditFacilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateCreditFacilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateCreditFacilityResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgCreateCreditFacilityResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateCreditFacilityResponse>, I>>(base?: I): MsgCreateCreditFacilityResponse {
    return MsgCreateCreditFacilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateCreditFacilityResponse>, I>>(
    object: I,
  ): MsgCreateCreditFacilityResponse {
    const message = createBaseMsgCreateCreditFacilityResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseMsgUpdateCreditFacility(): MsgUpdateCreditFacility {
  return { creator: "", facilityId: "", cribUserNic: "", status: 0, paymentHistory: [] };
}

export const MsgUpdateCreditFacility: MessageFns<MsgUpdateCreditFacility> = {
  encode(message: MsgUpdateCreditFacility, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.facilityId !== "") {
      writer.uint32(18).string(message.facilityId);
    }
    if (message.cribUserNic !== "") {
      writer.uint32(26).string(message.cribUserNic);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    for (const v of message.paymentHistory) {
      PaymentRecord.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateCreditFacility {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateCreditFacility();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.facilityId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cribUserNic = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.paymentHistory.push(PaymentRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateCreditFacility {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      facilityId: isSet(object.facilityId) ? globalThis.String(object.facilityId) : "",
      cribUserNic: isSet(object.cribUserNic) ? globalThis.String(object.cribUserNic) : "",
      status: isSet(object.status) ? facilityStatusFromJSON(object.status) : 0,
      paymentHistory: globalThis.Array.isArray(object?.paymentHistory)
        ? object.paymentHistory.map((e: any) => PaymentRecord.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MsgUpdateCreditFacility): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.facilityId !== "") {
      obj.facilityId = message.facilityId;
    }
    if (message.cribUserNic !== "") {
      obj.cribUserNic = message.cribUserNic;
    }
    if (message.status !== 0) {
      obj.status = facilityStatusToJSON(message.status);
    }
    if (message.paymentHistory?.length) {
      obj.paymentHistory = message.paymentHistory.map((e) => PaymentRecord.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateCreditFacility>, I>>(base?: I): MsgUpdateCreditFacility {
    return MsgUpdateCreditFacility.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateCreditFacility>, I>>(object: I): MsgUpdateCreditFacility {
    const message = createBaseMsgUpdateCreditFacility();
    message.creator = object.creator ?? "";
    message.facilityId = object.facilityId ?? "";
    message.cribUserNic = object.cribUserNic ?? "";
    message.status = object.status ?? 0;
    message.paymentHistory = object.paymentHistory?.map((e) => PaymentRecord.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMsgUpdateCreditFacilityResponse(): MsgUpdateCreditFacilityResponse {
  return { status: "", code: 0, message: "", data: "", requestId: "", timestamp: "" };
}

export const MsgUpdateCreditFacilityResponse: MessageFns<MsgUpdateCreditFacilityResponse> = {
  encode(message: MsgUpdateCreditFacilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateCreditFacilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateCreditFacilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateCreditFacilityResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: MsgUpdateCreditFacilityResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateCreditFacilityResponse>, I>>(base?: I): MsgUpdateCreditFacilityResponse {
    return MsgUpdateCreditFacilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateCreditFacilityResponse>, I>>(
    object: I,
  ): MsgUpdateCreditFacilityResponse {
    const message = createBaseMsgUpdateCreditFacilityResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.data = object.data ?? "";
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** CreateCreditFacility defines the CreateCreditFacility RPC. */
  CreateCreditFacility(request: MsgCreateCreditFacility): Promise<MsgCreateCreditFacilityResponse>;
  /** UpdateCreditFacility defines the UpdateCreditFacility RPC. */
  UpdateCreditFacility(request: MsgUpdateCreditFacility): Promise<MsgUpdateCreditFacilityResponse>;
}

export const MsgServiceName = "crib.creditfacility.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.CreateCreditFacility = this.CreateCreditFacility.bind(this);
    this.UpdateCreditFacility = this.UpdateCreditFacility.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  CreateCreditFacility(request: MsgCreateCreditFacility): Promise<MsgCreateCreditFacilityResponse> {
    const data = MsgCreateCreditFacility.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateCreditFacility", data);
    return promise.then((data) => MsgCreateCreditFacilityResponse.decode(new BinaryReader(data)));
  }

  UpdateCreditFacility(request: MsgUpdateCreditFacility): Promise<MsgUpdateCreditFacilityResponse> {
    const data = MsgUpdateCreditFacility.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateCreditFacility", data);
    return promise.then((data) => MsgUpdateCreditFacilityResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
