// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: crib/user/v1/crib_account.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "crib.user.v1";

/** CribAccount defines the CribAccount message. */
export interface CribAccount {
  nic: string;
  cribId: string;
  fullName: string;
  dateOfBirth: string;
  isActive: boolean;
  phoneNumber: string;
  email: string;
  nicFrontCid: string;
  nicBackCid: string;
  createdBy: string;
  createdAt: string;
  creator: string;
}

function createBaseCribAccount(): CribAccount {
  return {
    nic: "",
    cribId: "",
    fullName: "",
    dateOfBirth: "",
    isActive: false,
    phoneNumber: "",
    email: "",
    nicFrontCid: "",
    nicBackCid: "",
    createdBy: "",
    createdAt: "",
    creator: "",
  };
}

export const CribAccount: MessageFns<CribAccount> = {
  encode(message: CribAccount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nic !== "") {
      writer.uint32(10).string(message.nic);
    }
    if (message.cribId !== "") {
      writer.uint32(18).string(message.cribId);
    }
    if (message.fullName !== "") {
      writer.uint32(26).string(message.fullName);
    }
    if (message.dateOfBirth !== "") {
      writer.uint32(34).string(message.dateOfBirth);
    }
    if (message.isActive !== false) {
      writer.uint32(40).bool(message.isActive);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(50).string(message.phoneNumber);
    }
    if (message.email !== "") {
      writer.uint32(58).string(message.email);
    }
    if (message.nicFrontCid !== "") {
      writer.uint32(66).string(message.nicFrontCid);
    }
    if (message.nicBackCid !== "") {
      writer.uint32(74).string(message.nicBackCid);
    }
    if (message.createdBy !== "") {
      writer.uint32(82).string(message.createdBy);
    }
    if (message.createdAt !== "") {
      writer.uint32(90).string(message.createdAt);
    }
    if (message.creator !== "") {
      writer.uint32(98).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CribAccount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCribAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cribId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fullName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dateOfBirth = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nicFrontCid = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.nicBackCid = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.createdBy = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CribAccount {
    return {
      nic: isSet(object.nic) ? globalThis.String(object.nic) : "",
      cribId: isSet(object.cribId) ? globalThis.String(object.cribId) : "",
      fullName: isSet(object.fullName) ? globalThis.String(object.fullName) : "",
      dateOfBirth: isSet(object.dateOfBirth) ? globalThis.String(object.dateOfBirth) : "",
      isActive: isSet(object.isActive) ? globalThis.Boolean(object.isActive) : false,
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      nicFrontCid: isSet(object.nicFrontCid) ? globalThis.String(object.nicFrontCid) : "",
      nicBackCid: isSet(object.nicBackCid) ? globalThis.String(object.nicBackCid) : "",
      createdBy: isSet(object.createdBy) ? globalThis.String(object.createdBy) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: CribAccount): unknown {
    const obj: any = {};
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    if (message.cribId !== "") {
      obj.cribId = message.cribId;
    }
    if (message.fullName !== "") {
      obj.fullName = message.fullName;
    }
    if (message.dateOfBirth !== "") {
      obj.dateOfBirth = message.dateOfBirth;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.nicFrontCid !== "") {
      obj.nicFrontCid = message.nicFrontCid;
    }
    if (message.nicBackCid !== "") {
      obj.nicBackCid = message.nicBackCid;
    }
    if (message.createdBy !== "") {
      obj.createdBy = message.createdBy;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CribAccount>, I>>(base?: I): CribAccount {
    return CribAccount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CribAccount>, I>>(object: I): CribAccount {
    const message = createBaseCribAccount();
    message.nic = object.nic ?? "";
    message.cribId = object.cribId ?? "";
    message.fullName = object.fullName ?? "";
    message.dateOfBirth = object.dateOfBirth ?? "";
    message.isActive = object.isActive ?? false;
    message.phoneNumber = object.phoneNumber ?? "";
    message.email = object.email ?? "";
    message.nicFrontCid = object.nicFrontCid ?? "";
    message.nicBackCid = object.nicBackCid ?? "";
    message.createdBy = object.createdBy ?? "";
    message.createdAt = object.createdAt ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
