// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: crib/user/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { BankUser } from "./bank_user";
import { CribAccount } from "./crib_account";
import { Params } from "./params";

export const protobufPackage = "crib.user.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryGetCribAccountRequest defines the QueryGetCribAccountRequest message. */
export interface QueryGetCribAccountRequest {
  nic: string;
}

/** QueryGetCribAccountResponse defines the QueryGetCribAccountResponse message. */
export interface QueryGetCribAccountResponse {
  status: string;
  code: number;
  message: string;
  cribAccount: CribAccount | undefined;
  requestId: string;
  timestamp: string;
}

/** QueryAllCribAccountRequest defines the QueryAllCribAccountRequest message. */
export interface QueryAllCribAccountRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllCribAccountResponse defines the QueryAllCribAccountResponse message. */
export interface QueryAllCribAccountResponse {
  cribAccount: CribAccount[];
  pagination: PageResponse | undefined;
}

/** QueryGetBankUserRequest defines the QueryGetBankUserRequest message. */
export interface QueryGetBankUserRequest {
  bankId: string;
}

/** QueryGetBankUserResponse defines the QueryGetBankUserResponse message. */
export interface QueryGetBankUserResponse {
  bankUser: BankUser | undefined;
}

/** QueryAllBankUserRequest defines the QueryAllBankUserRequest message. */
export interface QueryAllBankUserRequest {
  pagination: PageRequest | undefined;
}

/** QueryAllBankUserResponse defines the QueryAllBankUserResponse message. */
export interface QueryAllBankUserResponse {
  bankUser: BankUser[];
  pagination: PageResponse | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetCribAccountRequest(): QueryGetCribAccountRequest {
  return { nic: "" };
}

export const QueryGetCribAccountRequest: MessageFns<QueryGetCribAccountRequest> = {
  encode(message: QueryGetCribAccountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nic !== "") {
      writer.uint32(10).string(message.nic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetCribAccountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetCribAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetCribAccountRequest {
    return { nic: isSet(object.nic) ? globalThis.String(object.nic) : "" };
  },

  toJSON(message: QueryGetCribAccountRequest): unknown {
    const obj: any = {};
    if (message.nic !== "") {
      obj.nic = message.nic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetCribAccountRequest>, I>>(base?: I): QueryGetCribAccountRequest {
    return QueryGetCribAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetCribAccountRequest>, I>>(object: I): QueryGetCribAccountRequest {
    const message = createBaseQueryGetCribAccountRequest();
    message.nic = object.nic ?? "";
    return message;
  },
};

function createBaseQueryGetCribAccountResponse(): QueryGetCribAccountResponse {
  return { status: "", code: 0, message: "", cribAccount: undefined, requestId: "", timestamp: "" };
}

export const QueryGetCribAccountResponse: MessageFns<QueryGetCribAccountResponse> = {
  encode(message: QueryGetCribAccountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.cribAccount !== undefined) {
      CribAccount.encode(message.cribAccount, writer.uint32(34).fork()).join();
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetCribAccountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetCribAccountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cribAccount = CribAccount.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetCribAccountResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      cribAccount: isSet(object.cribAccount) ? CribAccount.fromJSON(object.cribAccount) : undefined,
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
    };
  },

  toJSON(message: QueryGetCribAccountResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.cribAccount !== undefined) {
      obj.cribAccount = CribAccount.toJSON(message.cribAccount);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetCribAccountResponse>, I>>(base?: I): QueryGetCribAccountResponse {
    return QueryGetCribAccountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetCribAccountResponse>, I>>(object: I): QueryGetCribAccountResponse {
    const message = createBaseQueryGetCribAccountResponse();
    message.status = object.status ?? "";
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.cribAccount = (object.cribAccount !== undefined && object.cribAccount !== null)
      ? CribAccount.fromPartial(object.cribAccount)
      : undefined;
    message.requestId = object.requestId ?? "";
    message.timestamp = object.timestamp ?? "";
    return message;
  },
};

function createBaseQueryAllCribAccountRequest(): QueryAllCribAccountRequest {
  return { pagination: undefined };
}

export const QueryAllCribAccountRequest: MessageFns<QueryAllCribAccountRequest> = {
  encode(message: QueryAllCribAccountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllCribAccountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllCribAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllCribAccountRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllCribAccountRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllCribAccountRequest>, I>>(base?: I): QueryAllCribAccountRequest {
    return QueryAllCribAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllCribAccountRequest>, I>>(object: I): QueryAllCribAccountRequest {
    const message = createBaseQueryAllCribAccountRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllCribAccountResponse(): QueryAllCribAccountResponse {
  return { cribAccount: [], pagination: undefined };
}

export const QueryAllCribAccountResponse: MessageFns<QueryAllCribAccountResponse> = {
  encode(message: QueryAllCribAccountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.cribAccount) {
      CribAccount.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllCribAccountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllCribAccountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cribAccount.push(CribAccount.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllCribAccountResponse {
    return {
      cribAccount: globalThis.Array.isArray(object?.cribAccount)
        ? object.cribAccount.map((e: any) => CribAccount.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllCribAccountResponse): unknown {
    const obj: any = {};
    if (message.cribAccount?.length) {
      obj.cribAccount = message.cribAccount.map((e) => CribAccount.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllCribAccountResponse>, I>>(base?: I): QueryAllCribAccountResponse {
    return QueryAllCribAccountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllCribAccountResponse>, I>>(object: I): QueryAllCribAccountResponse {
    const message = createBaseQueryAllCribAccountResponse();
    message.cribAccount = object.cribAccount?.map((e) => CribAccount.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryGetBankUserRequest(): QueryGetBankUserRequest {
  return { bankId: "" };
}

export const QueryGetBankUserRequest: MessageFns<QueryGetBankUserRequest> = {
  encode(message: QueryGetBankUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bankId !== "") {
      writer.uint32(10).string(message.bankId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetBankUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetBankUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bankId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetBankUserRequest {
    return { bankId: isSet(object.bankId) ? globalThis.String(object.bankId) : "" };
  },

  toJSON(message: QueryGetBankUserRequest): unknown {
    const obj: any = {};
    if (message.bankId !== "") {
      obj.bankId = message.bankId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetBankUserRequest>, I>>(base?: I): QueryGetBankUserRequest {
    return QueryGetBankUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetBankUserRequest>, I>>(object: I): QueryGetBankUserRequest {
    const message = createBaseQueryGetBankUserRequest();
    message.bankId = object.bankId ?? "";
    return message;
  },
};

function createBaseQueryGetBankUserResponse(): QueryGetBankUserResponse {
  return { bankUser: undefined };
}

export const QueryGetBankUserResponse: MessageFns<QueryGetBankUserResponse> = {
  encode(message: QueryGetBankUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bankUser !== undefined) {
      BankUser.encode(message.bankUser, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetBankUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetBankUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bankUser = BankUser.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetBankUserResponse {
    return { bankUser: isSet(object.bankUser) ? BankUser.fromJSON(object.bankUser) : undefined };
  },

  toJSON(message: QueryGetBankUserResponse): unknown {
    const obj: any = {};
    if (message.bankUser !== undefined) {
      obj.bankUser = BankUser.toJSON(message.bankUser);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetBankUserResponse>, I>>(base?: I): QueryGetBankUserResponse {
    return QueryGetBankUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetBankUserResponse>, I>>(object: I): QueryGetBankUserResponse {
    const message = createBaseQueryGetBankUserResponse();
    message.bankUser = (object.bankUser !== undefined && object.bankUser !== null)
      ? BankUser.fromPartial(object.bankUser)
      : undefined;
    return message;
  },
};

function createBaseQueryAllBankUserRequest(): QueryAllBankUserRequest {
  return { pagination: undefined };
}

export const QueryAllBankUserRequest: MessageFns<QueryAllBankUserRequest> = {
  encode(message: QueryAllBankUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllBankUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllBankUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllBankUserRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllBankUserRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllBankUserRequest>, I>>(base?: I): QueryAllBankUserRequest {
    return QueryAllBankUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllBankUserRequest>, I>>(object: I): QueryAllBankUserRequest {
    const message = createBaseQueryAllBankUserRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllBankUserResponse(): QueryAllBankUserResponse {
  return { bankUser: [], pagination: undefined };
}

export const QueryAllBankUserResponse: MessageFns<QueryAllBankUserResponse> = {
  encode(message: QueryAllBankUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.bankUser) {
      BankUser.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllBankUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllBankUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bankUser.push(BankUser.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllBankUserResponse {
    return {
      bankUser: globalThis.Array.isArray(object?.bankUser) ? object.bankUser.map((e: any) => BankUser.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllBankUserResponse): unknown {
    const obj: any = {};
    if (message.bankUser?.length) {
      obj.bankUser = message.bankUser.map((e) => BankUser.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllBankUserResponse>, I>>(base?: I): QueryAllBankUserResponse {
    return QueryAllBankUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllBankUserResponse>, I>>(object: I): QueryAllBankUserResponse {
    const message = createBaseQueryAllBankUserResponse();
    message.bankUser = object.bankUser?.map((e) => BankUser.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** ListCribAccount Queries a list of CribAccount items. */
  GetCribAccount(request: QueryGetCribAccountRequest): Promise<QueryGetCribAccountResponse>;
  /** ListCribAccount defines the ListCribAccount RPC. */
  ListCribAccount(request: QueryAllCribAccountRequest): Promise<QueryAllCribAccountResponse>;
  /** ListBankUser Queries a list of BankUser items. */
  GetBankUser(request: QueryGetBankUserRequest): Promise<QueryGetBankUserResponse>;
  /** ListBankUser defines the ListBankUser RPC. */
  ListBankUser(request: QueryAllBankUserRequest): Promise<QueryAllBankUserResponse>;
}

export const QueryServiceName = "crib.user.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.GetCribAccount = this.GetCribAccount.bind(this);
    this.ListCribAccount = this.ListCribAccount.bind(this);
    this.GetBankUser = this.GetBankUser.bind(this);
    this.ListBankUser = this.ListBankUser.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  GetCribAccount(request: QueryGetCribAccountRequest): Promise<QueryGetCribAccountResponse> {
    const data = QueryGetCribAccountRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetCribAccount", data);
    return promise.then((data) => QueryGetCribAccountResponse.decode(new BinaryReader(data)));
  }

  ListCribAccount(request: QueryAllCribAccountRequest): Promise<QueryAllCribAccountResponse> {
    const data = QueryAllCribAccountRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListCribAccount", data);
    return promise.then((data) => QueryAllCribAccountResponse.decode(new BinaryReader(data)));
  }

  GetBankUser(request: QueryGetBankUserRequest): Promise<QueryGetBankUserResponse> {
    const data = QueryGetBankUserRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBankUser", data);
    return promise.then((data) => QueryGetBankUserResponse.decode(new BinaryReader(data)));
  }

  ListBankUser(request: QueryAllBankUserRequest): Promise<QueryAllBankUserResponse> {
    const data = QueryAllBankUserRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListBankUser", data);
    return promise.then((data) => QueryAllBankUserResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
